### PR TITLE
release artifacts for release v0.2.1

### PR DESCRIPTION
**Pull request by akartsky**
Release Notes Draft:

Added new resources for SageMaker Studio 

- New resource `Domain`
- New resource `UserProfile`
- New resource `App`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ryansteakley — APPROVED** [review]

**Comment by ryansteakley** [comment]
Are you going to update the readme in this pr or in a separate one?

**Comment by akartsky** [comment]
> Are you going to update the readme in this pr or in a separate one?

Done

**Pull request closed without merging**
