### PR TITLE
terminal codes clean up

### PR DESCRIPTION
**Pull request by surajkota**
Description of changes:

Be conservative in the list of terminal codes. Specify only those for which the user needs to change a value in spec.
  - looked at each resource's APIs errors and removed the ones that are not thrown in any of the CRUD APIs

Long pending backlog item

Testing:
will rely on PR Build

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ryansteakley — APPROVED** [review]

**Comment by mbaijal** [comment]
> will rely on PR Build

do have any integration tests for any of these cases ?

**Review by mbaijal — APPROVED** [review]
Trust your analysis here @surajkota

**Comment by surajkota** [comment]
> question unrelated to your change: do have any integration tests for any of these cases ?

will be converted in unit tests

**Pull request merged**
