### PR TITLE
Update AWS SDK Go to v1.37.31

### PR DESCRIPTION
**Pull request by RedbackThomson**
Updating from v1.35.5
Adding all the new re:Invent features

All integration tests passed

### CODE REVIEW

**Comment by mbaijal** [comment]
Shouldn't the sdk version update require us to ignore more resources in the generator.yaml file or have all new resources_names already been added there ?

**Comment by RedbackThomson** [comment]
> Shouldn't the sdk version update require us to ignore more resources in the generator.yaml file or have all new resources_names already been added there ?

It seems that between 1.37.4 and 1.37.31 there were no additional resources.

**Review by mbaijal — APPROVED** [review]
LGTM considering it is generated code and tests are passing.

**Comment by surajkota** [comment]
note this upgrade is actually from 1.35.5 to 1.37.31. v1.37.4 in current master's go.mod is in-correct since we were building off a hack to override the go-sdk version
the reason you don't see resources needed to be added to generator.yaml because those were added in a previous PR

**Review by jaypipes — APPROVED** [review]
All looks good to me. Feel free to merge.

**Pull request merged**
