### PR TITLE
release artifacts for release v0.4.1

### PR DESCRIPTION
**Pull request by ryansteakley**
Release Notes Draft:
Fixes bug with training-job in which training job with a profileRuleConfiguration but without a debugRuleConfiguration the controller crashes.

- Changes custom set defaults function to compare only profileRuleConfiguration.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by surajkota — APPROVED** [review]
/approve
/lgtm

**Comment by A-Hilaly** [comment]
looks like it's a `gIthub.com/gopkg.in` hiccup
/retest

**Pull request merged**
