### PR TITLE
Add reduced test flakiness to Canary

### PR DESCRIPTION
**Pull request by ryansteakley**
Merge in reduced test flakiness to Canary branch

### CODE REVIEW

**Comment by RedbackThomson** [comment]
This appears to need rebasing?

**Review by surajkota — CHANGES_REQUESTED** [review]
We cant merge these changes to canary since we want to test the released version. Requesting to create a new revision with only the following changes:
- revert this commit - 8cfdfe2669d2bedc955af4205d7a40f2debfb7a7
- only include changes from `test/e2e/__init__.py`
```
rand = random.randrange(1, 4)
time.sleep(rand)
```

**Comment by ryansteakley** [comment]
reopen

**Pull request merged**
